"""Audit script — surveys ctxforge to inform voussoir's integration plan.

Outputs a Markdown report with:
  • Inventory of Protocols in `ctxforge.protocols.*`
  • Inventory of services in `ctxforge.engine.services.*`
  • Quick "looks-active vs looks-experimental" heuristic per service
    (heuristic: services referenced from `engine/factory.py` are active)
  • Async-vs-sync surface check on every Protocol method
  • Identifier of `Optional[Any]` slots in EngineDeps that need tightening
"""

from __future__ import annotations

import importlib
import inspect
import pkgutil
from pathlib import Path

REPORT = Path(__file__).resolve().parent.parent / "docs/audits/ctxforge-2026-05.md"


def main() -> None:
    lines: list[str] = ["# ctxforge audit (2026-05)\n"]
    lines.append("Auto-generated by `scripts/ctxforge_audit.py`.\n")

    lines.append("\n## Protocols\n")
    import ctxforge.protocols as protos_pkg

    for _, name, _ in pkgutil.iter_modules(protos_pkg.__path__):
        mod = importlib.import_module(f"ctxforge.protocols.{name}")
        protos = [
            obj
            for _, obj in inspect.getmembers(mod, inspect.isclass)
            if getattr(obj, "_is_runtime_protocol", False)
            or "Protocol" in (obj.__bases__[0].__name__ if obj.__bases__ else "")
        ]
        for p in protos:
            methods = [m for m, _ in inspect.getmembers(p, predicate=inspect.isfunction)]
            lines.append(f"- `{p.__module__}.{p.__name__}` — methods: {methods}")

    lines.append("\n## Services in `engine/services/`\n")
    services_pkg = importlib.import_module("ctxforge.engine.services")
    services_init = services_pkg.__file__
    if services_init is None:
        raise RuntimeError("ctxforge.engine.services has no __file__ — cannot locate factory.py")
    factory_src = (Path(services_init).parent.parent / "factory.py").read_text()
    for _, name, _ in pkgutil.iter_modules(services_pkg.__path__):
        active = name in factory_src
        marker = "✓ used by factory" if active else "⚠ not referenced in factory.py"
        lines.append(f"- `{name}` — {marker}")

    lines.append("\n## EngineDeps `Optional[Any]` slots\n")
    deps_src = (Path(services_init).parent.parent / "deps.py").read_text()
    for line in deps_src.splitlines():
        if "Optional[Any]" in line:
            lines.append(f"- {line.strip()}")

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines))
    print(f"Wrote {REPORT}")


if __name__ == "__main__":
    main()
